<?php
/**
 * SubtleForms ISO-3166 Country List
 *
 * @package SubtleForms\Fields
 * @since   1.0.0
 */

namespace SubtleForms\Fields;

/**
 * Provides full ISO-3166 country list for Country field.
 */
final class CountryList {

	/**
	 * Get full list of countries with ISO-3166 codes.
	 *
	 * @return array Array of ['code' => 'name'] pairs
	 */
	public static function getAll(): array {
		return array(
			'AF' => __( 'Afghanistan', 'subtleforms' ),
			'AL' => __( 'Albania', 'subtleforms' ),
			'DZ' => __( 'Algeria', 'subtleforms' ),
			'AS' => __( 'American Samoa', 'subtleforms' ),
			'AD' => __( 'Andorra', 'subtleforms' ),
			'AO' => __( 'Angola', 'subtleforms' ),
			'AI' => __( 'Anguilla', 'subtleforms' ),
			'AQ' => __( 'Antarctica', 'subtleforms' ),
			'AG' => __( 'Antigua and Barbuda', 'subtleforms' ),
			'AR' => __( 'Argentina', 'subtleforms' ),
			'AM' => __( 'Armenia', 'subtleforms' ),
			'AW' => __( 'Aruba', 'subtleforms' ),
			'AU' => __( 'Australia', 'subtleforms' ),
			'AT' => __( 'Austria', 'subtleforms' ),
			'AZ' => __( 'Azerbaijan', 'subtleforms' ),
			'BS' => __( 'Bahamas', 'subtleforms' ),
			'BH' => __( 'Bahrain', 'subtleforms' ),
			'BD' => __( 'Bangladesh', 'subtleforms' ),
			'BB' => __( 'Barbados', 'subtleforms' ),
			'BY' => __( 'Belarus', 'subtleforms' ),
			'BE' => __( 'Belgium', 'subtleforms' ),
			'BZ' => __( 'Belize', 'subtleforms' ),
			'BJ' => __( 'Benin', 'subtleforms' ),
			'BM' => __( 'Bermuda', 'subtleforms' ),
			'BT' => __( 'Bhutan', 'subtleforms' ),
			'BO' => __( 'Bolivia', 'subtleforms' ),
			'BA' => __( 'Bosnia and Herzegovina', 'subtleforms' ),
			'BW' => __( 'Botswana', 'subtleforms' ),
			'BR' => __( 'Brazil', 'subtleforms' ),
			'BN' => __( 'Brunei', 'subtleforms' ),
			'BG' => __( 'Bulgaria', 'subtleforms' ),
			'BF' => __( 'Burkina Faso', 'subtleforms' ),
			'BI' => __( 'Burundi', 'subtleforms' ),
			'KH' => __( 'Cambodia', 'subtleforms' ),
			'CM' => __( 'Cameroon', 'subtleforms' ),
			'CA' => __( 'Canada', 'subtleforms' ),
			'CV' => __( 'Cape Verde', 'subtleforms' ),
			'KY' => __( 'Cayman Islands', 'subtleforms' ),
			'CF' => __( 'Central African Republic', 'subtleforms' ),
			'TD' => __( 'Chad', 'subtleforms' ),
			'CL' => __( 'Chile', 'subtleforms' ),
			'CN' => __( 'China', 'subtleforms' ),
			'CO' => __( 'Colombia', 'subtleforms' ),
			'KM' => __( 'Comoros', 'subtleforms' ),
			'CG' => __( 'Congo', 'subtleforms' ),
			'CD' => __( 'Congo, Democratic Republic', 'subtleforms' ),
			'CK' => __( 'Cook Islands', 'subtleforms' ),
			'CR' => __( 'Costa Rica', 'subtleforms' ),
			'HR' => __( 'Croatia', 'subtleforms' ),
			'CU' => __( 'Cuba', 'subtleforms' ),
			'CY' => __( 'Cyprus', 'subtleforms' ),
			'CZ' => __( 'Czech Republic', 'subtleforms' ),
			'DK' => __( 'Denmark', 'subtleforms' ),
			'DJ' => __( 'Djibouti', 'subtleforms' ),
			'DM' => __( 'Dominica', 'subtleforms' ),
			'DO' => __( 'Dominican Republic', 'subtleforms' ),
			'EC' => __( 'Ecuador', 'subtleforms' ),
			'EG' => __( 'Egypt', 'subtleforms' ),
			'SV' => __( 'El Salvador', 'subtleforms' ),
			'GQ' => __( 'Equatorial Guinea', 'subtleforms' ),
			'ER' => __( 'Eritrea', 'subtleforms' ),
			'EE' => __( 'Estonia', 'subtleforms' ),
			'ET' => __( 'Ethiopia', 'subtleforms' ),
			'FJ' => __( 'Fiji', 'subtleforms' ),
			'FI' => __( 'Finland', 'subtleforms' ),
			'FR' => __( 'France', 'subtleforms' ),
			'GA' => __( 'Gabon', 'subtleforms' ),
			'GM' => __( 'Gambia', 'subtleforms' ),
			'GE' => __( 'Georgia', 'subtleforms' ),
			'DE' => __( 'Germany', 'subtleforms' ),
			'GH' => __( 'Ghana', 'subtleforms' ),
			'GR' => __( 'Greece', 'subtleforms' ),
			'GD' => __( 'Grenada', 'subtleforms' ),
			'GT' => __( 'Guatemala', 'subtleforms' ),
			'GN' => __( 'Guinea', 'subtleforms' ),
			'GW' => __( 'Guinea-Bissau', 'subtleforms' ),
			'GY' => __( 'Guyana', 'subtleforms' ),
			'HT' => __( 'Haiti', 'subtleforms' ),
			'HN' => __( 'Honduras', 'subtleforms' ),
			'HK' => __( 'Hong Kong', 'subtleforms' ),
			'HU' => __( 'Hungary', 'subtleforms' ),
			'IS' => __( 'Iceland', 'subtleforms' ),
			'IN' => __( 'India', 'subtleforms' ),
			'ID' => __( 'Indonesia', 'subtleforms' ),
			'IR' => __( 'Iran', 'subtleforms' ),
			'IQ' => __( 'Iraq', 'subtleforms' ),
			'IE' => __( 'Ireland', 'subtleforms' ),
			'IL' => __( 'Israel', 'subtleforms' ),
			'IT' => __( 'Italy', 'subtleforms' ),
			'JM' => __( 'Jamaica', 'subtleforms' ),
			'JP' => __( 'Japan', 'subtleforms' ),
			'JO' => __( 'Jordan', 'subtleforms' ),
			'KZ' => __( 'Kazakhstan', 'subtleforms' ),
			'KE' => __( 'Kenya', 'subtleforms' ),
			'KI' => __( 'Kiribati', 'subtleforms' ),
			'KP' => __( 'Korea, North', 'subtleforms' ),
			'KR' => __( 'Korea, South', 'subtleforms' ),
			'KW' => __( 'Kuwait', 'subtleforms' ),
			'KG' => __( 'Kyrgyzstan', 'subtleforms' ),
			'LA' => __( 'Laos', 'subtleforms' ),
			'LV' => __( 'Latvia', 'subtleforms' ),
			'LB' => __( 'Lebanon', 'subtleforms' ),
			'LS' => __( 'Lesotho', 'subtleforms' ),
			'LR' => __( 'Liberia', 'subtleforms' ),
			'LY' => __( 'Libya', 'subtleforms' ),
			'LI' => __( 'Liechtenstein', 'subtleforms' ),
			'LT' => __( 'Lithuania', 'subtleforms' ),
			'LU' => __( 'Luxembourg', 'subtleforms' ),
			'MK' => __( 'Macedonia', 'subtleforms' ),
			'MG' => __( 'Madagascar', 'subtleforms' ),
			'MW' => __( 'Malawi', 'subtleforms' ),
			'MY' => __( 'Malaysia', 'subtleforms' ),
			'MV' => __( 'Maldives', 'subtleforms' ),
			'ML' => __( 'Mali', 'subtleforms' ),
			'MT' => __( 'Malta', 'subtleforms' ),
			'MH' => __( 'Marshall Islands', 'subtleforms' ),
			'MR' => __( 'Mauritania', 'subtleforms' ),
			'MU' => __( 'Mauritius', 'subtleforms' ),
			'MX' => __( 'Mexico', 'subtleforms' ),
			'FM' => __( 'Micronesia', 'subtleforms' ),
			'MD' => __( 'Moldova', 'subtleforms' ),
			'MC' => __( 'Monaco', 'subtleforms' ),
			'MN' => __( 'Mongolia', 'subtleforms' ),
			'ME' => __( 'Montenegro', 'subtleforms' ),
			'MA' => __( 'Morocco', 'subtleforms' ),
			'MZ' => __( 'Mozambique', 'subtleforms' ),
			'MM' => __( 'Myanmar', 'subtleforms' ),
			'NA' => __( 'Namibia', 'subtleforms' ),
			'NR' => __( 'Nauru', 'subtleforms' ),
			'NP' => __( 'Nepal', 'subtleforms' ),
			'NL' => __( 'Netherlands', 'subtleforms' ),
			'NZ' => __( 'New Zealand', 'subtleforms' ),
			'NI' => __( 'Nicaragua', 'subtleforms' ),
			'NE' => __( 'Niger', 'subtleforms' ),
			'NG' => __( 'Nigeria', 'subtleforms' ),
			'NO' => __( 'Norway', 'subtleforms' ),
			'OM' => __( 'Oman', 'subtleforms' ),
			'PK' => __( 'Pakistan', 'subtleforms' ),
			'PW' => __( 'Palau', 'subtleforms' ),
			'PS' => __( 'Palestine', 'subtleforms' ),
			'PA' => __( 'Panama', 'subtleforms' ),
			'PG' => __( 'Papua New Guinea', 'subtleforms' ),
			'PY' => __( 'Paraguay', 'subtleforms' ),
			'PE' => __( 'Peru', 'subtleforms' ),
			'PH' => __( 'Philippines', 'subtleforms' ),
			'PL' => __( 'Poland', 'subtleforms' ),
			'PT' => __( 'Portugal', 'subtleforms' ),
			'QA' => __( 'Qatar', 'subtleforms' ),
			'RO' => __( 'Romania', 'subtleforms' ),
			'RU' => __( 'Russia', 'subtleforms' ),
			'RW' => __( 'Rwanda', 'subtleforms' ),
			'KN' => __( 'Saint Kitts and Nevis', 'subtleforms' ),
			'LC' => __( 'Saint Lucia', 'subtleforms' ),
			'VC' => __( 'Saint Vincent and the Grenadines', 'subtleforms' ),
			'WS' => __( 'Samoa', 'subtleforms' ),
			'SM' => __( 'San Marino', 'subtleforms' ),
			'ST' => __( 'Sao Tome and Principe', 'subtleforms' ),
			'SA' => __( 'Saudi Arabia', 'subtleforms' ),
			'SN' => __( 'Senegal', 'subtleforms' ),
			'RS' => __( 'Serbia', 'subtleforms' ),
			'SC' => __( 'Seychelles', 'subtleforms' ),
			'SL' => __( 'Sierra Leone', 'subtleforms' ),
			'SG' => __( 'Singapore', 'subtleforms' ),
			'SK' => __( 'Slovakia', 'subtleforms' ),
			'SI' => __( 'Slovenia', 'subtleforms' ),
			'SB' => __( 'Solomon Islands', 'subtleforms' ),
			'SO' => __( 'Somalia', 'subtleforms' ),
			'ZA' => __( 'South Africa', 'subtleforms' ),
			'ES' => __( 'Spain', 'subtleforms' ),
			'LK' => __( 'Sri Lanka', 'subtleforms' ),
			'SD' => __( 'Sudan', 'subtleforms' ),
			'SR' => __( 'Suriname', 'subtleforms' ),
			'SZ' => __( 'Swaziland', 'subtleforms' ),
			'SE' => __( 'Sweden', 'subtleforms' ),
			'CH' => __( 'Switzerland', 'subtleforms' ),
			'SY' => __( 'Syria', 'subtleforms' ),
			'TW' => __( 'Taiwan', 'subtleforms' ),
			'TJ' => __( 'Tajikistan', 'subtleforms' ),
			'TZ' => __( 'Tanzania', 'subtleforms' ),
			'TH' => __( 'Thailand', 'subtleforms' ),
			'TL' => __( 'Timor-Leste', 'subtleforms' ),
			'TG' => __( 'Togo', 'subtleforms' ),
			'TO' => __( 'Tonga', 'subtleforms' ),
			'TT' => __( 'Trinidad and Tobago', 'subtleforms' ),
			'TN' => __( 'Tunisia', 'subtleforms' ),
			'TR' => __( 'Turkey', 'subtleforms' ),
			'TM' => __( 'Turkmenistan', 'subtleforms' ),
			'TV' => __( 'Tuvalu', 'subtleforms' ),
			'UG' => __( 'Uganda', 'subtleforms' ),
			'UA' => __( 'Ukraine', 'subtleforms' ),
			'AE' => __( 'United Arab Emirates', 'subtleforms' ),
			'GB' => __( 'United Kingdom', 'subtleforms' ),
			'US' => __( 'United States', 'subtleforms' ),
			'UY' => __( 'Uruguay', 'subtleforms' ),
			'UZ' => __( 'Uzbekistan', 'subtleforms' ),
			'VU' => __( 'Vanuatu', 'subtleforms' ),
			'VA' => __( 'Vatican City', 'subtleforms' ),
			'VE' => __( 'Venezuela', 'subtleforms' ),
			'VN' => __( 'Vietnam', 'subtleforms' ),
			'YE' => __( 'Yemen', 'subtleforms' ),
			'ZM' => __( 'Zambia', 'subtleforms' ),
			'ZW' => __( 'Zimbabwe', 'subtleforms' ),
		);
	}

	/**
	 * Get countries formatted for select options.
	 *
	 * @return array Array of ['value' => 'code', 'label' => 'name']
	 */
	public static function getOptions(): array {
		$countries = self::getAll();
		$options   = array();

		foreach ( $countries as $code => $name ) {
			$options[] = array(
				'value' => $code,
				'label' => $name,
			);
		}

		return $options;
	}
}
